version: '3.8'

services:
  tradeloop-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - NODE_ENV=production
    image: tradeloop-frontend:production
    container_name: tradeloop-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      - VITE_WS_URL=${VITE_WS_URL:-ws://localhost:3000}
    volumes:
      # SSL certificates for HTTPS
      - ./ssl:/etc/nginx/ssl:ro
      # Nginx logs
      - ./logs:/var/log/nginx
      # Custom nginx config if needed
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - tradeloop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  # Reverse proxy with SSL termination (optional)
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - tradeloop-network
    restart: unless-stopped
    depends_on:
      - tradeloop-frontend

networks:
  tradeloop-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nginx-logs:
    driver: local
  ssl-certs:
    driver: local