[build]
  publish = "dist"
  command = "npm ci && npm run build"
  base = "frontend"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://tradeloop-api.onrender.com"
  VITE_APP_TITLE = "TradeLoop"
  VITE_ENVIRONMENT = "production"
  NODE_VERSION = "18"