[build]
  publish = "dist"
  command = "npm run build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://tradeloop-api.onrender.com"
  NODE_VERSION = "18"