[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci && npm run build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://tradeloop-api.onrender.com"
  VITE_APP_TITLE = "TradeLoop"
  VITE_ENVIRONMENT = "production"
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "https://tradeloop-api.onrender.com"